### ISSUE TITLE
Communicate with tracker

### ISSUE THREAD

**Issue by BrickGoat** [BrickGoat/BitBrick#1]
**Description**  
The ‘announce’ key in the .torrent metafile gives you the url of the tracker. The tracker is an HTTP(S) service that holds information about the torrent and peers. The tracker itself does not have the file you want to download, but it does have a list of all peers that are connected for this torrent who have the file or are downloading the file. It responds to GET requests with a list of peers.
- [x] Read Metainfo file
  - [x] Decode file with bencode [lib](https://pypi.org/project/bencode.py/) into dictionary
  - [x] Extract info and announce keys
- [x] Make request to announce URL
  - [x]  Create 20 byte Hash from info dictionary with [sha1](https://docs.python.org/3/library/hashlib.html)
  - [x] Create 20 byte peer_id in  Azureus(-,clientID,version_num,-) format
  - [x] Make request with UDP announce URL using [this](https://www.bittorrent.org/beps/bep_0015.html) spec:
    - [x] Extract udp name and port from announce url
    - [x] Create connection packet
    - [x] Read connection response packet
    - [x] Create announce packet
    - [x] Read announce response packet
    - [x] Retransmit requests if no response
- [ ] Interpret Response
  - [x] Error handling for faliure reason and warning message keys
  - [ ] Save interval, tracker_id, peers
